### ISSUE TITLE
Learn more about how to use the software

### ISSUE THREAD

**Issue by MengYuDream** [UlyssesWu/FreeMote#107]
First of all, thank you very much for making this software, which is very convenient to use and very powerful.
Recently, I am obsessed with Stable Diffusion. When I made the Tachie LORA model, I used a lot of galgame Tachie materials.
All in all, is there any way to export the frames in PSB running your software? When using screenshots, the surroundings are completely dark, and it is often necessary to use PS to cut out and clean up the material, and a lot of details are lost due to the use of screenshots.
I am a novice user, sorry to have to ask you for advice.
Is there some advanced way of using the software, like running transparently, or being able to export a still frame directly from within instead of taking a screenshot with an external screenshot software.
I don't quite understand how to implement these functions.

**Comment by UlyssesWu** [comment]
duplicate of #53 . I haven't implement #53 feature (low priority & lack of time). 

It's a question more about the usage of EMT engine & Graphic APIs, rather than FreeMote.
You could learn the basic usage of EMT engine (maybe refer to FMV) and then implement your tool.
Render on a DX canvas, and then export as images. Not that hard. Just need some time to implement. Good luck.

**Comment by MengYuDream** [comment]
> 所有者

understood, thanks and good luck
