### ISSUE TITLE
[Question]It worked in 3.5, but not in 3.6.

### ISSUE THREAD

**Issue by mymzc4njm** [UlyssesWu/FreeMote#111]
Game: アマカノ2＋, PC

Hello, UlyssesWu.
Thanks for your help as always.
I have a question.

I'm going to convert the PSZ to a PSB, and then convert that to MMO.
It worked in 3.5, but not in 3.6.
EmtConvert is fine, but not EmtMake.

Could you check it out?

**Comment by UlyssesWu** [comment]
This should be fixed in latest CI build, try: https://ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts

It seems that you're the guy named ixnjexnjk on pinkdarker. 
So you're using FreeMote to get mmo (the only way to achieve this on this world), 
then importing into the editor and exporting tachie CGs aren't you? 😉
(It's ok as long as you're not making profit from them.)
