### ISSUE TITLE
[PsbDecompile] Occultic;Nine PS Vita & PS4 scenario decompile issue

### ISSUE THREAD

**Issue by Gunoshozo** [UlyssesWu/FreeMote#128]
Hey.
I've tried to unpack scenario files of Occultic;nine from PSV and PS4 and encountered similar issue for both platforms.
Here is the command that I've used:
`psbdecompile info-psb -k nx5ik27w2scm7 scenario_info.psb.m -a`
Tried it on master and on latest release.
It looks like all the files are generated as pairs of json and resx.json, but for object/resourse "mmm22" it only outputs  mmm22.ks with garbage data.
I've debugged master build a little and here is the little hack that made it possible to generate valid files:
```
if (possibleFileName.StartsWith("mmm22") && possibleFileName == possibleFileNames[0])
 {
      ms = MsManager.GetStream(bodyBytes);
     continue;
}
```
Iserted it into the following line: https://github.com/UlyssesWu/FreeMote/blob/d9f9caecc592b6e7b3cd83402e40dc10f03c250c/FreeMote.PsBuild/PsbDecompiler.cs#L748

It has something to do with order of names in a list or something like that. For other MMMs name that is used to generate file is the first in the array, and for mmm22 it's the second name, so by skipping first it "fixes" the issue. IDK what proper solution for this case should look like :/

[O;N ps4 sample.zip](https://github.com/UlyssesWu/FreeMote/files/15370217/O.N.ps4.sample.zip)
[O;N ps vita samples.zip](https://github.com/UlyssesWu/FreeMote/files/15370219/O.N.ps.vita.samples.zip)

cmd output is nothing special:
![image](https://github.com/UlyssesWu/FreeMote/assets/51006468/70a50932-77c8-43aa-a099-cc917c895157)

**Comment by UlyssesWu** [comment]
Thanks for the issue report. 

In fact, just as what I've commented in code, there is no obvious rule (or the rule is too random) of the real file name to be used as key, that's why we have to try every "possibleName"s.
Usually only the correct one "possibleName" will lead to a successful decryption & decompression, but for this "mmm22" file, it also works with a wrong "possibleName" - because it just happens to be decompress-able after a wrong decryption. 😪

I will tweak the possibleNames rule, and add a check to avoid bad decompression.
