### ISSUE TITLE
[PsBuild] Problems with the game ANONYMOUS;CODE after compiling the scenario_body.bin file 

### ISSUE THREAD

**Issue by petrowitch88** [UlyssesWu/FreeMote#133]
Good afternoon, I'm translating the game ANONYMOUS;CODE (PC) into another language. I figured out where to find the key for unpacking, grabbed all text from the *ks.scn.m.json files, but after changing the text to the translated and compiling the archive, I had problems. 

The game starts crashing at random points in time. I don't understand what it depends on. I compared the original files and the translated ones - the file structure is the same, all variables are left as they are, and even the floating comma operators are unchanged.

I do not know how to get crash reports from the game, so I am acting blindly.

I don't understand what I'm doing wrong. 

But for now, I have one thought. I compared the scenario_info.psb.m.json files from the Japanese version and from the English version. They contain different variables in square brackets. What do they mean? After all, this file is created by the PsBuild, and then, as far as I understand, it is used to package the file.

I am attaching here an archive with some modified files, and the original ones that turned out after decompilation (it is impossible to throw off the entire scenario due to restrictions on the size of attached files)

[ac_scenario.zip](https://github.com/user-attachments/files/16737609/ac_scenario.zip)

**Comment by UlyssesWu** [comment]
> They contain different variables in square brackets. What do they mean? 
The start position and length to find a specific file in `.bin`. It's not related to your problem.

Just based on these files, I don't think it's a FreeMote problem. You've to find out the real crash reason first. 
Maybe find a crash dump file and analyze it.
If you can't, you should at least do some experiments. 
e.g. Only change 1 character in 1 file and repack; Do not change anything just extract and repack; etc.

**Comment by petrowitch88** [comment]
Unfortunately, the game does not leave any crash reports. 

I repacked the archive in two versions at once, one without making changes to this file, the other with changing two letters in the text. Both crash some time after the start of the game.

It is also striking that the archive unpacked by the utility and packed back by it differs in size from the original file (40,674,733 bytes from the original, 42,077,168 bytes from the repackaged version) . Maybe the archive sizes are checked somewhere in the exe, I do not know.

**Comment by petrowitch88** [comment]
Sorry, I accidentally closed the topic. 

To unpack, I used the command
.\PsbDecompile.exe info-psb -k 5fWhAHt4zVn2X scenario_info.psb.m -a
packing with this
.\PsBuild info-psb scenario_info.psb.m.json

**Comment by UlyssesWu** [comment]
Try `.\PsbDecompile.exe info-psb -k 5fWhAHt4zVn2X scenario_info.psb.m` and repack (without `-a`).

**Comment by petrowitch88** [comment]
> Try `.\PsbDecompile.exe info-psb -k 5fWhAHt4zVn2X scenario_info.psb.m` and repack (without `-a`).

The resulting file is still different from the original one, 40,791,851 bytes. The game crashes steadily after twenty minutes of play.

**Comment by UlyssesWu** [comment]
There is no guarantee of size consistency. More or less if you edit something, you will make the pack size different.
AFAIK size change is fine for most games. 

If you can play for 20 mins, I guess the repacked files are already loaded an working. Then you have to fix the crash by yourself.

Since there is already another translators successfully handled the game (for zh-cn language) with FreeMote, I'm pretty sure it's not a FreeMote issue. I know they were working on the NS ver but that shouldn't make any difference - or they would have the size issue, too. See: https://github.com/UlyssesWu/FreeMote/issues/85

In there blog, they did mentioned that editing images (using RGBA images instead of BC7) would make the game crash after some time. I don't know if it's useful to you but anyway, good luck. Feel free to reopen this if you have more clues.

**Comment by UlyssesWu** [comment]
Related project: https://github.com/kurikomoe/AnonymousCode_CHS
Keep in mind to mention their names if their code helps.
