### ISSUE TITLE
[Request]Add support to Castlevania The Adventure ReBirth - Wiiware

### ISSUE THREAD

**Issue by evil-trainer** [UlyssesWu/FreeMote#139]
Hello! First of all I'd like to thank you for the amazing tool freemote is!

I tried Freemote on Castlevania the Adventure on the Wii and it somewhat extracted the pictures of some of the .psb files, but it errored out in several of them. Also, the ones it managed to extract were a bit pixelated or with completely scrambled results (maybe a swizzle issue?). The ones that produced errors didn't output any images at all.

Here's the comparison of results from Freemote and Dolphin (by dumping the textures with the emulator feature):
![Castlevania](https://github.com/user-attachments/assets/aef0220b-d089-4d87-81d3-701686a229bc)

The .psb that couldn't be extracted, produced this error:
![Erro](https://github.com/user-attachments/assets/731513c6-3be9-4531-bf5d-cb777cbcc460)

Finally, I'm attaching the .psb samples so they can be looked at. Thanks in advance!
[Castlevania the Adventure ReBirth .PSB files.zip](https://github.com/user-attachments/files/17876176/Castlevania.the.Adventure.ReBirth.PSB.files.zip)

**Comment by evil-trainer** [comment]
I'm so happy right now, Mr. Wu! 😭😭😭😭
It's been months since I started trying to find a way to extract these textures so I could translate the game to my language! And now, thanks to your amazing tool, I'll finally be able to do it! Thank you very much!!


![logo_us-texture](https://github.com/user-attachments/assets/5d957614-2f04-447b-a1bd-e0c46bc2e44f)
![logo-texture](https://github.com/user-attachments/assets/351bcb85-a429-43ff-8c31-8313325c943b)
![rebirth-texture](https://github.com/user-attachments/assets/75ffd5b3-115e-4611-b8ba-f701de77bf1e)
![key-texture](https://github.com/user-attachments/assets/da585db9-462b-4d2c-8677-6551e783084c)
![system-texture](https://github.com/user-attachments/assets/0814b714-3961-414b-81c1-9a1b789c9164)
![font-texture](https://github.com/user-attachments/assets/ec2ce1ea-b6d7-499d-96ea-3832b49b1edd)

**Comment by evil-trainer** [comment]
I'll close this since it has been fixed =)

**Comment by UlyssesWu** [comment]
I think I haven't fixed the font unclear issue... But I haven't found any problem on that actually. My code looks correct.
If someone knows why the font color (CI4 format) looks strange, please let me know.

**Comment by evil-trainer** [comment]
> I think I haven't fixed the font unclear issue... But I haven't found any problem on that actually. My code looks correct. If someone knows why the font color (CI4 format) looks strange, please let me know.

Yeah, I noticed that too. But honestly, like you said, it doesn't seem to be a problem. I wonder if I just replace the extracted image with the one from Dolphin (after I edit to insert my characters, of course) I'll make it work as it should...

I'll give it a try!

P.S.: this is how some of the images are supposed to be extracted, right? I'm assuming they're assembled by the game during runtime, right?

![1 -bg6](https://github.com/user-attachments/assets/a59d000e-2739-470c-9654-edc7dec5d695)
![3 -moon](https://github.com/user-attachments/assets/9e98f3ce-dd4d-42f5-b47b-5f6083b5d529)
![4 -sky6](https://github.com/user-attachments/assets/fb4c5556-4383-4971-b8e6-89130988cb4e)

**Comment by UlyssesWu** [comment]
@evil-trainer 
> I wonder if I just replace the extracted image with the one from Dolphin (after I edit it to insert my characters, of course) I'll make it work as it should...
You have to do more than that. If you checked the font's json file you'd know the image is using `CI4` format. 
That's a image with palette. You cannot just replace it with a common 32bpp image or you will see a warning when PsBuild.
There're 2 choices:

1. Make a 4BppIndexed image (with palette). That's kind of hard because I even don't know which tool can do this (without writing code by myself to generate such images). In Photoshop you can use "Save for Web (Legacy)" to export a PNG-8 (8BppIndexed, CI8) but not a PNG-4.
2. Edit the json file `"type": "CI4"` to `"type": "RGBA8"` (or `RGB5A3`) and remove `"pal": "#resource#*"`. Or use `CI8` with PS: Save for Web, PNG-8, 256 colors)

The latter is eaiser but will take more memory, but for most games it should be ok.

> this is how some of the images are supposed to be extracted, right?

I have no idea, either. It can be, because it's map tiles, can be devided to 10x10 tiles. But I'm not sure.
If you won't ever edit them and you want to avoid any problem, the best choice is do not decompile and recompile them.
If you are using `PsbDecompile info-psb`, you can extract PSBs without adding `-a`. 
Then, you just choose the PSBs you must edit, decompile and recompile and then replace them. 
Finally you repack with `PsBuild info-psb`. By this way you kept those PSBs untouched.

**Comment by evil-trainer** [comment]
Oh, I see!

Then I guess the best approach is indeed the .json editing method. I guess I'll just edit the .extracted  png and rebuild it with freemote then.

About the 10x10 tiles images, thankfully I won't have to mess with that since my project is about translation, so I'll mainly focus on UI textures and such.

I'm currently trying to figure out all the .json flags and stuff so I can manipulate font glyphs and other UI text. I'll try to start with the "NOW LOADING" text and replace it with "CARREGANDO". It seems to be a straightforward process: the image is a 32x32 png with the 8 unique letters that form the "NOW LOADING" text.

I'll have to learn to do that first, though 😅

**Comment by UlyssesWu** [comment]
Usually, you should also provide the original PSB file, not just the decompiled files. But for this time, the problem is simple: It's not an [Emote PSB](https://github.com/UlyssesWu/FreeMote/wiki/Viewer#emt-psb).

FreeMote Viewer is only for EMT PSBs.
EMT PSB is a sub type of Motion PSB. Not all Motion PSBs are EMT PSB.
Check the decompiled json, if there is no "metadata" with "bustControl" etc., it's not an EMT PSB, and won't be able to view.

There is no known tool to view a non-EMT Motion PSB.

**Comment by evil-trainer** [comment]
> Usually, you should also provide the original PSB file, not just the decompiled files. But for this time, the problem is simple: It's not an [Emote PSB](https://github.com/UlyssesWu/FreeMote/wiki/Viewer#emt-psb).
> 
> FreeMote Viewer is only for EMT PSBs. EMT PSB is a sub type of Motion PSB. Not all Motion PSBs are EMT PSB. Check the decompiled json, if there is no "metadata" with "bustControl" etc., it's not an EMT PSB, and won't be able to view.
> 
> There is no known tool (in public) to view a non-EMT Motion PSB.

Oh, I see then. I did read the wiki but couldn't completely understand all the specification of the format.

For now, I'm coding some (very) basic python tool to just play the animations, so I can now where to place my edited texture icons inside the texture atlas. But I couldn't get the colors and effects (transparency, alignment, etc) to play correctly.

https://github.com/user-attachments/assets/d14c24cb-de60-4f2f-8220-b7aad4128e6d

Compared to the actual animations, my implementation is WAY off, but I guess it should do if I just intend to have a visual cue as to where I can position my edited icons on-screen.

https://streamable.com/9ylkkr

I wonder if it's possible to render the animation correclty outside the game's code 🤔

**Comment by UlyssesWu** [comment]
No. The MotionPlayer animation engine is kind of like Adobe Flash. It's complex (a.k.a. full of trash). For now I don't want to waste my time on re-creating such an self-made animation engine. I created EmtMake in order to edit EMT models with the official editor (limited), but EmtMake only works for EMT PSBs for now.
You may be able to load these Motion PSBs with official MotionPlayer.dll, however AFAIK there're only krkr versions on Windows platform, which means you have to make a krkr project and figure out how to load them. That sounds time-wasting. too.

Your tool looks very good. You can continue polishing it. There is one thing: The MotionPlayer engine have 2 kind of animations: tween and deform (just like Flash). While tween is easy to implement, deform might be harder.
