### ISSUE TITLE
Support files larger than 2GB

### ISSUE THREAD

**Issue by Coxxs** [UlyssesWu/FreeMote#43]
When extracting `image_body.bin` (3.72GB) from a PS4 game, PSB Decompiler returns:
```
X:\konosuba-PS4> PsbDecompile info-psb -k 38757621acf82 image_info.psb.m -l 131
...
Extracting info from image_info.psb.m ...
System.IO.IOException: 该文件太长。此操作当前仅限于支持大小小于 2 GB 的文件。
   在 System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   在 FreeMote.Tools.PsbDecompile.Program.<>c__DisplayClass0_3.<Main>b__6()
Done.
```

Extracting other smaller files, such as `motion_body.bin` (201MB), running smoothly:
```
X:\konosuba-PS4> PsbDecompile info-psb -k 38757621acf82 motion_info.psb.m -l 131
...
Extracting info from motion_info.psb.m ...
66 files extracted.
Done.
```

Tried set `gcAllowVeryLargeObjects` to `true` as mentioned [here](https://stackoverflow.com/questions/26882004/system-io-file-readallbytes-for-file-larger-than-2gb), but still reports same error. 

Example files: https://mega.nz/folder/9Y0kHQQQ#DQKtb4mnMwtVPM6Ek4t52A

(Just extracting some images for fun, maybe not an important issue for now.)

**Comment by UlyssesWu** [comment]
Yes, I have a plan to make FreeMote more efficient using modern C#. Will try to solve this issue later.

**Comment by UlyssesWu** [comment]
Fixed. Try the [latest CI build](https://ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts).

If you don't process the file on a SSD, the Disk IO would be the bottleneck when extracting. Otherwise, the CPU / RAM would be. 
If you encounter an OutOfMemory Exception, you can use `-1by1` to process sequentially (could be very slow though).
Their would be some warnings about `Resource Index conflict`, just ignore them.
If you just care about CG images, you can use `info-psb` without `-a` for `.psb.m` extraction, then use `image <dir path>` for images extraction.

如果你不在固态硬盘上处理这个文件，磁盘IO速度会成为效率瓶颈。在 7200转机械硬盘 / i7 8750H 上，使用`-a`参数处理这个PSB，需要8分40秒，而换到固态硬盘会节省一半的时间。
与此同时，瞬时内存占用会超过4GB，因此从这个版本起，FreeMote默认以64位编译（FMV除外），如果需要在x86的老PC上运行，可手动以x86编译。
如果你内存不够大或CPU核数少，可以用`-1by1`来要求对archive PSB中打包的每个文件进行串行处理（默认并行），通常来说这会很慢。
处理过程中会报一些警告`Resource Index conflict`，这是因为有些PSB中存在资源复用，不影响提取。
如果你其实不需要json输出，通常建议是不使用`-a`参数，先得到所有的`.psb.m`文件，再执行`PsbDecompile image <image文件夹路径>`来进行文件夹提取，这样输出的结果只有合并后的图片，没有json和切片图片。

**Comment by Coxxs** [comment]
Thanks for the update & tips! Seems only arm windows PC need x86 apps nowadays ;) 
`PsbDecompile info-psb` & `PsbDecompile image image` running very well on my x64 computer.
