### ISSUE TITLE
[PsbDecompile/PsBuild] Troubles with font (ttf)

### ISSUE THREAD

**Issue by TheEZIC** [UlyssesWu/FreeMote#55]
I try to decompile this files (key is 523aad2de7132):
[FontPSBs.zip](https://github.com/UlyssesWu/FreeMote/files/6254348/FontPSBs.zip)
When i used this command it's throw exciption.
./PsbDecompile.exe -raw info-psb -k 523aad2de7132 ../font_info.psb.m
But when i used this command with -raw flag it's works, but the files list don't match with font_info.psb.m.json
In json I have: tt_humming-d.ttf.m
In folder I have: tt_humming-d.ttf.m.psb.m
I try to use exm2lib and it gave to me tt_humming-d.ttf.m
I put it in the directory which FreeMote decompiled files and delete tt_humming-d.ttf.m.psb.m
After that I used PsBuild. He did his job successfully, but when I launch game it's crash.
Such problems were not observed with other files that did not contain fonts.

**Comment by TheEZIC** [comment]
With the other psb.m and bin, everything worked, even if I made changes.

**Comment by UlyssesWu** [comment]
For a quick workaround, maybe you can just use `tt_humming-d.ttf.m.psb.m` (extracted with `-raw`) instead of `tt_humming-d.ttf.m` (extracted with exm2lib). The `.psb.m` will be removed when packing so you will still get a correct repack.

PSB is a bad file format with many inconsistent designs, therefore this bug comes. 
I will make PsBuild work for this PSB without using `-raw`.

**Comment by UlyssesWu** [comment]
Should be fixed now. Try with latest CI build.

**Comment by TheEZIC** [comment]
Can you please build release. I don't know much about dotnet.

**Comment by UlyssesWu** [comment]
# FreeMote
[![Build Status](https://ci.appveyor.com/api/projects/status/github/UlyssesWu/FreeMote?branch=master&svg=true)](https://ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts)

**Comment by TheEZIC** [comment]
Ok, thank you
