### ISSUE TITLE
[mfl][and] Ahoge Chanbara psb.m files issue

### ISSUE THREAD

**Issue by MishaIac** [UlyssesWu/FreeMote#64]
Ahoge Chanbara is a game developed by M2 in 2013 (iOS) and 2014 (Android)

Of course I understand that the game is already quite old, but will there be support for the files of this game? They have psb.m extension and have "mfl" in the header, while some have "mdf" in the header, but they also do not decompile.

Here is an archive with samples "mfl" and "mdf":
[ahoge_chanbara.zip](https://github.com/UlyssesWu/FreeMote/files/6941116/ahoge_chanbara.zip)

**Comment by UlyssesWu** [comment]
`psb.m` = [MT19937 MDF](https://github.com/UlyssesWu/FreeMote/wiki/PSB-Shells,-Types,-Platforms#mdf-mt19937). It must be decrypted with a key. A key is a hex string like `523aad2de7132` or `38757621acf82`. If you managed to find it (usually in game dlls), you can try the mdf file first (because mfl signature is not accepted for now).

`EmtConvert mdf {file} -k {key} -l 131`

If you cannot find the key, I may have a look into that game one day, but I don't have much spare time for now.

**Comment by MishaIac** [comment]
Not necessary. I just thought that these files were somehow compressed, but since they need a key, you don't need to bother with it. Anyway, thanks for your reply. Good luck!

**Comment by MishaIac** [comment]
By the way, I still managed to find the key for the archives of this game
Key: Rj9Pegoh4 (it is worth noting that the key consists of 9 characters, not 13 as usual)
Length: 97 (0x61)
mdf files are decrypted and unpacked without problems, but mfl is recognized by EmtConvert as mdf, and the output is a 1kb file with `"""""""""""0` inside.

**Comment by UlyssesWu** [comment]
All things should work now, including:
1. mfl: just like mdf (mt19937), but uses **F**ast**L**Z compression instead of **d**e**f**late.
2. map: `e_viewer.psb.m` is a "map" type PSB. Now images (tile) can be extraced.
3. ogg/wav: audio files can be extracted from `game.psb.m`.

Since it's a game developed by M2, I doubt these special designs are just used in their only one or two games, perhaps it's not even worth my time. 
I downloaded that game for research, and then [FreeMote.FastLz](https://github.com/UlyssesWu/FreeMote.FastLz) was made for mfl. Anyway, I think I should focus more on newer PSBs rather than those made in 2017. Maybe M2 already abandoned those designs after that single try.
