### ISSUE TITLE
[PsBuild] use combined image to compile for `Tachie` image type

### ISSUE THREAD

**Issue by TheEZIC** [UlyssesWu/FreeMote#66]
I tried to translate a certain game but ran into a problem.
I decompiled pictures using this command:
./PsbDecompile image_name.psb
This command created a folder with an image splitted into chunks(and with a combined image). I translated the picture chunks, but the builder broke it.
It would be wonderful if it was possible to work with such images via "image" and "link" commands, cuz working with chunks is such a pain in the ass
I saw same problem in this issue:
#40

**Comment by UlyssesWu** [comment]
> but the builder broke it

Couldn't understand what this means, but get your main point. 
It sounds possible, but will take some time of course.

**Comment by TheEZIC** [comment]
> > but the builder broke it
> 
> Couldn't understand what this means

Output image receives visual artifacts if I decompile compiled file

**Comment by UlyssesWu** [comment]
> Output image receives visual artifacts if I decompile compiled psb file

Still cannot understand. Why don't you upload samples and screenshots?

**Comment by TheEZIC** [comment]
I have this pictures in my decompiled folder:
![image](https://user-images.githubusercontent.com/35061249/129444843-71936c06-6c31-4557-aad2-86685635937c.png)
First image is combined one. Second and third is chunks. They have a different size in contrast to the combined one (I tried to put one on top of the other in photoshop).
Then I tried to drow random lines on 2rd chunk.
The compiler gave me this:
![image](https://user-images.githubusercontent.com/35061249/129444904-18b6f651-0d9b-4c31-aabc-24717b0abca3.png)
As you can see in the screenshot. In the combined image, the first chunk (not modified) became normal, but the modified one did't.

**Comment by UlyssesWu** [comment]
> Why don't you upload **samples** **and** screenshots?

Just Upload PSB

**Comment by TheEZIC** [comment]
[psb.zip](https://github.com/UlyssesWu/FreeMote/files/6986428/psb.zip)

**Comment by UlyssesWu** [comment]
Tried and it works as expected. This screenshot shows the images extracted from recompiled PSB.
![image](https://user-images.githubusercontent.com/4312781/129445859-03a7803a-6eff-4e83-8b6d-3a955d154120.png)

The possible problem, is that you may have changed chunk images' size. Anyway, unless you can provide a more clear reproduce steps with samples, I will not spend more time on this "builder broke it" issue.

And I must emphasize that you should have provided the PSB samples since your first post if you want the issue to be fixed ASAP. The issue template has stated that. It's already figured out that you're trying to make a Russian translation of [Go-Toubun no Hanayome](https://vk.com/hanayome5?w=wall-124140060_36649) (without mentioning FreeMote through) so don't hide a thing and just provide PSB before asking questions next time.

**Comment by TheEZIC** [comment]
> And I must emphasize that you should have provided the PSB samples since your first post if you want the issue to be fixed ASAP. The issue template has stated that. It's already figured out that you're trying to make a Russian translation of Go-Toubun no Hanayome (without mentioning FreeMote though) so don't hide a thing and just provide PSB before asking questions next time.
Ok, sorry for that. I thought that your tool is allowed only for personal use, and not for public translations. Next time I will attach PSD files. I will also mention your tool in the posts, if you don't mind of course. Please accept my apologies again. A little later I will describe the steps that I did about the "builder broke it" issue

**Comment by TheEZIC** [comment]
1) I decompile the original psb file using this command:
.\PsbDecompile.exe ./ebg06a.psb.m
2) I change the chunk image(ebg06a-1).
After which I try to transfer the same changes to the combined image(ebg06a).
But I can't make the changes in the same places on the combined image, since the combined image has a width of 1920, and the chunk is 2048.(Also, if you add up the heights of the two chunks, their sum will not match the height of the combined image.)
3) I build a psb file using this command:
./PsBuild.exe ./ebg06a.psb.m.json
4) I decompile the psb file obtained in step 3 with the command:
.\PsbDecompile.exe ./ebg06a.psb.m.pure.psb
5) I open the folder and see those visual artifacts that were in the screenshots above.
I also tried to change only the combined image in step 3, but it led to the same results.

**Comment by UlyssesWu** [comment]
> I change the chunk image(ebg06a-1).

This is the most unclear (and unable to reproduce) part. 
I have said "you may have changed chunk images' size". Have you done that? The `ebg06a-1` is 2048x1024, after change, it should still be 2048x1024.

**Comment by TheEZIC** [comment]
Yep, it's still 2048x1024
![image](https://user-images.githubusercontent.com/35061249/129450167-df364e56-e73e-45ea-96c9-335c3ea7fce6.png)
And after changes too
![image](https://user-images.githubusercontent.com/35061249/129450178-05e25fc3-1d25-4609-b9c2-f0e5fe2aa4ae.png)

**Comment by UlyssesWu** [comment]
If you have upload files in the first picture with your reproduce steps, things may have been clear and you won't have to post these screenshots. "Always attach samples."

However, it's still lucky enough for you and me because your first screenshot has indicated the issue. Have you compared your 2 screenshots? Did you find one is "24" and another is "32"? After that, you may go back and check the decompiled result at beginning. So it's because you have changed image format.

**Comment by TheEZIC** [comment]
Right now I've drawn only red strokes, but I think there is some problem with RGB channels
![image](https://user-images.githubusercontent.com/35061249/129450360-2ed4dca0-d559-478b-9bc9-64a751610f1a.png)

**Comment by TheEZIC** [comment]
Okay The problem really was in the bit depth of the color. I would never have thought of it myself. Thanks for the help. ^_^

**Comment by UlyssesWu** [comment]
From now on, PsbDecompile will only extract combined images from image (`Tachie`) PSB, unless `-dci` (`--disable-combined-image`) is specified. 

PsBuild is now able to build `Tachie` PSB from combined images. And it can still build from chunk images if you've decompiled with `-dci`.
