### ISSUE TITLE
[Question] [Amaemi] This PSB file can't view. Why?

### ISSUE THREAD

**Issue by fkvldh** [UlyssesWu/FreeMote#86]
* Read [wiki](https://github.com/UlyssesWu/FreeMote/wiki)
* Provide game name and platform (PC/Android/PSP etc.)
* Provide PSB file samples
* Program output, or screenshots

Game name: アマエミ (https://vndb.org/v32183)
PC, Artemis engine

(Sorry for bad English)
"iro_0.psb" can't view(FreeMoteViewer). And mmo file(EmtMake) can't open E-mote Free Movie Maker.
I don't know why, maybe encrypted?
Can I decryption? But I don't know cryptKey...

![photo01](https://user-images.githubusercontent.com/46631481/177012918-603765ba-275c-4a1f-b5ae-34a272a0d84b.png)
[iro_0.zip](https://github.com/UlyssesWu/FreeMote/files/9033420/iro_0.zip)

**Comment by UlyssesWu** [comment]
This is an encrypted PSB, but since it's PSBv4, FreeMoteViewer (and PsbDecompile) can still handle it with my Dullahan Load tech (load/unpack encrypted PSBv3+ models, but unable to repack unless you find the key).

So, it's not caused by encryption.

<img width="944" alt="image" src="https://user-images.githubusercontent.com/4312781/177022191-0518101f-c924-4d2b-a5e7-7dc16e6eb6a6.png">

In fact, the model is rendered, but not at the (0,0) position. They set those textures to be shown at (10.5, 1069) . Because of that, you have to drag the canvas until the "Center" (indicates the center point position) in title bar reach (-10.5, -1069) , then you would see the model.

I have no idea why they made models like this. Maybe a kind of "obfuscation". But this may slightly affect the performace in a bad way if they didn't configure a correct clipping size...

<img width="533" alt="image" src="https://user-images.githubusercontent.com/4312781/177022435-8329e42b-5192-48de-ad60-3bdf418b2318.png">

**Comment by fkvldh** [comment]
Thanks, UlyssesWu.
This is あざらしそふと(developer)'s frist try e-mote. So maybe it could have been difficult to make.
Or because Artemis engine? I don't know why too.

**Comment by fkvldh** [comment]
> 

Thanks, UlyssesWu.
This is あざらしそふと(developer)'s frist try e-mote. So maybe it could have been difficult to make.
Or because Artemis engine? I don't know why too.

**Comment by fkvldh** [comment]
> This is an encrypted PSB, but since it's PSBv4, FreeMoteViewer (and PsbDecompile) can still handle it with my Dullahan Load tech (load/unpack encrypted PSBv3+ models, but unable to repack unless you find the key).
> 
> So, it's not caused by encryption.
> 
> <img alt="image" width="944" src="https://user-images.githubusercontent.com/4312781/177022191-0518101f-c924-4d2b-a5e7-7dc16e6eb6a6.png">
> 
> In fact, the model is rendered, but not at the (0,0) position. They set those textures to be shown at (10.5, 1069) . Because of that, you have to drag the canvas until the "Center" (indicates the center point position) in title bar reached (-10.5, -1069) , then you would see the model.
> 
> I have no idea why they made models like this. Maybe a kind of "obfuscation". But this may slightly affect the performace in a bad way if they didn't configure a correct clipping size...
> 
> <img alt="image" width="533" src="https://user-images.githubusercontent.com/4312781/177022435-8329e42b-5192-48de-ad60-3bdf418b2318.png">

Thanks, UlyssesWu.
This is あざらしそふと(developer)'s frist try e-mote. So maybe it could have been difficult to make.
Or because Artemis engine? I don't know why too.
